### ISSUE TITLE
'>', '<', '>>' segfaults in redirection tests 

### ISSUE THREAD

**Issue by jadbouzaien** [cacharle/minishell_test#14] opened 2021-02-18 11:34 UTC
Those 3 tests segfaults in the tester but they doesn't do that when i try `./minishell -c ">"` for an example in my program.

**Comment by cacharle** [comment] 2021-02-19 08:30
Did you try as indicated in the README <https://github.com/cacharle/minishell_test#environement-variables>? (with the `try` script at the root of this repo)  
The main use of this script is to ensure that your environment variable are the same as the test, I don't see how those could influence the `>` test but you never know.

**Comment by jadbouzaien** [comment] 2021-02-20 10:11
I tried with the `./try` script it worked, the issue comes only in the `./run` script

**Comment by cacharle** [comment] 2021-02-20 13:48
Well I downloaded your minishell (<https://github.com/amadene-git/minishell>) and it didn't segfault with the test on my machine.

I got the following output:

```
|> WITH >
|  STATUS: expected 1 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: -c: line 1: syntax error near unexpected token `newline'$
minishell: -c: line 1: `>'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH >>
|  STATUS: expected 1 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: -c: line 1: syntax error near unexpected token `newline'$
minishell: -c: line 1: `>>'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH <
|  STATUS: expected 1 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: -c: line 1: syntax error near unexpected token `newline'$
minishell: -c: line 1: `<'$
|---------------------------------------ACTUAL----------------------------------
================================================================================
```

And when a test segfaults the status code is generaly `-11`.

Could you send me your log in `result.log` for thoses tests?

How do you know that they sefault in my test?

**Comment by jadbouzaien** [comment] 2021-02-20 18:34
When i try the test i get 
```
|> WITH >
|  STATUS: expected 2 actual -11
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH >>
|  STATUS: expected 2 actual -11
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH <
|  STATUS: expected 2 actual -11
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================
```
I'm using a mac for the tests

**Comment by cacharle** [comment] 2021-02-20 19:58
Hmm, that's weird and it doesn't segfault on Linux, I'll try again when I have access to a mac in a few days.

Maybe try running valgrind on it (i.e `valgrind ./minishell -c '>'`) to see if you have any `Invalid read` or other memory access error that valgrind detects but don't always cause a segfault.

You could also try with `llbd` (i.e `lldb ./minishell` then `run -c '>'`), similarly your program may crash in the debugger but not when you run it.

**Comment by cacharle** [comment] 2021-02-24 06:41
Well I'm on a mac at school and I get a similar result:

```
|> WITH >
|  STATUS: expected 2 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH >>
|  STATUS: expected 2 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================

|> WITH <
|  STATUS: expected 2 actual 0
|---------------------------------------EXPECTED--------------------------------
minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
================================================================================
```

Your mac has something different from the school's one.  
Or your minishell on github isn't the same as the one on your local machine.
Either way, I can't really help you with a bug I can't reproduce.

**Comment by jadbouzaien** [comment] 2021-02-25 17:56
I'm on Big Sur, maybe it's because of that!
Thanks anyway ^^

**Comment by cacharle** [comment] 2021-02-25 18:08
I'm closing this but feel free to pm me on Slack if you found a may to fix it.

**Closed as completed by cacharle** 2021-02-25 18:08 UTC
